### ISSUE TITLE
Hide only subpages outputted by Subpagelist in sidebar 

### ISSUE THREAD

**Issue by dennisfrank** [flokosiol/kirby-subpagelist#5]
When using Subpagelist’s filter functionality it would be nice to hide only the filtered subpages in Kirbys sidebar. 
### Why?

I try to use Subpagelist to display subpages as sections of page ([similar to the _official_ one-pager solution](http://getkirby.com/docs/solutions/one-pager)). I am looking for a way to display page sections and real sub pages separately.

**Comment by flokosiol** [comment]
Hiding the pages in the sidebar of the panel is a core functionality of Kirby. I will close that issue because I think it's not related to this plugin.

I found a nice solution how to handle subpages as sections in combination with normal subpages. It's a combination of this subpagelist plugin, a customized version of @timoetting 's [list field](https://github.com/TimOetting/kirby-list-field) and some panel hook magic. But it needs some (more) explanation … I hope I will find the time to write an article about it :) Maybe this would be an option for you?

Here's a quick preview (with german panel):

![kirby-subpage-sections](https://cloud.githubusercontent.com/assets/11918336/11929179/2cf7e43e-a7d9-11e5-874d-7d2a368b1155.png)
